add multi-stage taxi trip to SaoPauloTaxiPredictor
eqasim-org/eqasim-java pull request #194
Opened 2024-02-19 03:35 UTC by MayuriAnn

As suggested in https://github.com/eqasim-org/eqasim-java/issues/191#issuecomment-1950041727, I followed the code on https://github.com/eqasim-org/eqasim-java/blob/a8a73b53dbfc085e6eabddcd8ba43fd72013b063/core/src/main/java/org/eqasim/core/simulation/mode_choice/utilities/predictors/CarPredictor.java#L36-L45 to update the code of SaoPauloTaxiPredictor class.

2024-02-19 07:56 UTC, balacmi requested changes
Thank you for looking into this. Can you please address my above comments and I will merge the PR.

2024-02-19 07:56 UTC, balacmi commented on sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/predictors/SaoPauloTaxiPredictor.java
> +		double taxiTravelTime_min = parameters.car.constantParkingSearchPenalty_min;
Can you please remove this line as it is only used for car trips and for for taxis.

2024-02-19 07:56 UTC, balacmi commented on sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/predictors/SaoPauloTaxiPredictor.java
> +		double accessEgressTime_min = parameters.car.additionalAccessEgressWalkTime_min;
Same as above

2024-02-19 07:56 UTC, balacmi commented on sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/predictors/SaoPauloTaxiPredictor.java
> +		this.parameters = parameters;
ModeParameters object is for now not used, please remove it (see below my further comments).

2024-02-20 13:36 UTC, MayuriAnn commented
Please check if its correct now.

2024-02-20 13:49 UTC, balacmi approved these changes
Looks good, thank you.

2024-02-20 13:51 UTC, balacmi commented
May I also ask you to add to the `CHANGELOG.md` file the update you made, so we can keep track of what changed between releases.

2024-02-20 14:33 UTC, balacmi approved these changes
Great

2024-02-20 14:51 UTC, merged